### ISSUE TITLE
Board size is unknown

### ISSUE THREAD

**Issue by lackmorrison** [coseyfannitutti/mysterium#1]
JLCPCB is not able to determine pcb size based on **mysterium.zip** archive. Please specify pcb size in readme 
![jlcerror](https://user-images.githubusercontent.com/49443091/75343700-0f252a80-58aa-11ea-9666-8e900adb2c81.png)

**Comment by coseyfannitutti** [comment]
It's simply because it's a large board with a large drill file, and jlc's timeout limit sometimes doesn't give it enough time to process.

You will need to enter the dimensions manually (147mm*348mm).
