### ISSUE TITLE
Question about standoff heights in Mysterium case.

### ISSUE THREAD

**Issue by nchieng** [coseyfannitutti/mysterium#15]
https://github.com/coseyfannitutti/mysterium/blob/master/case/README.md#L25-L26

Calls for standoffs:
14mm for the case
8mm for the feet

Stacking the case layers, it totals 20mm 
Stacking the feet layers, it totals 12mm

Was there a reason why shorter standoffs were prescribed?

**Comment by dhanakane** [comment]
Are you taking into account that the top and bottom layers are only for the screws to pass through? The standoffs do not pass through all the layers of the case.

**Comment by nchieng** [comment]
No, I'm not accounting for the screws to pass through.
If the screws pass through Top-1 and Bottom,
How are these pieces held in place?

**Comment by dhanakane** [comment]
The screws are only 4mm. So you have 4mm screw --> 14mm standoff <-- 4mm screw. About 2mm of the thread engages the standoff on each side. The top and bottom sides of acrylic have smaller holes that only allow the screw body to pass through but a standoff cannot.

**Comment by nchieng** [comment]
I think I get it. Thanks for the explanation!

So the top and bottom layers are essentially getting clamped by the screw caps and the standoffs.

![image](https://user-images.githubusercontent.com/29188449/94562047-301e8580-02a8-11eb-9456-d69316977290.png)

**Comment by dhanakane** [comment]
Yes! And the acrylic layers the screw threads pass through. The standoffs
align the case and provide a body for the screws to thread into as well.

**Comment by coseyfannitutti** [comment]
That table is great. So, yes the standoff area length is ~15mm, and 14mm standoffs are used because of the slight variance in layer thickness of cast acrylic sheets.

It is the same for the feet, with ~9mm standoff area length, so 8mm standoffs are used.

**Comment by nchieng** [comment]
Thanks! That now makes sense to me.

Here's the same table for the feet.
![image](https://user-images.githubusercontent.com/29188449/94632656-83c3ba00-030e-11eb-8d17-6c7bb0f52ad8.png)

**Comment by nchieng** [comment]
@coseyfannitutti 
Sorry to keep this alive. Can you point me in the right direction for the clear bumpons users at the bottom of the case please?

**Comment by dhanakane** [comment]
They’re very similar to these “3M Bumpon Protective Products SJ5312 Blister of 56”

They’re widely used in domestic applications.
