### ISSUE TITLE
Right side column (SW15,SW32,SW49,SW94) not working

### ISSUE THREAD

**Issue by lednax** [coseyfannitutti/mysterium#26]
Hey @coseyfannitutti, I recently built a Mysterium (No iso) but the right side column isn't working. I tested for continuity based on the schematics and it appears there IS continuity but wanted to get your expert opinion. The rest of the kb works fine. 

Screenshot of the column: 
![2021-02-13 06_13_27-Window](https://user-images.githubusercontent.com/17058888/107843450-84cb2480-6da1-11eb-9bd0-b0c9ddceb957.png)

Thank you in advance. I bet you get a ton of these.

**Comment by lednax** [comment]
I tested continuity again and I'm leaning towards a software issue. Is the `default` qmk not good for v1?

**Comment by this-snow** [comment]
Did you tested continuity up to the Controller? And continuity between the diodes, that are for this column. 
There is no software issue.

**Comment by lednax** [comment]
Checked continuity again up to the controller and it was fine but then noticed a bent leg on the controller so I got it out an fixed that. Works fine now.
