### ISSUE TITLE
Question on Nav-Acrylic.dxg

### ISSUE THREAD

**Issue by ytkwong** [coseyfannitutti/mysterium#4]
Hey, the specs for nav-acrylic file seems to be off, it is showing me as 296.3mm x 180.6mm.

I just realized it might be an issue with Ponoko's website. Could i get the dimensions specs for the basic acrylic guards is it supposed to be 348.6mm (width) for acrylic guard and kit plate and 61mm for nav?

And is the plate file missing the "~" key? or it's just not showing on Ponoko

**Comment by coseyfannitutti** [comment]
The plate has now been fixed. Please update the repository or redownload for the correct files.

Plate and acrylic guard width: 347.7mm
Nav guard width: 61mm

I'm not sure how that cutout was removed when exporting, but thanks for pointing it out.
