### ISSUE TITLE
windows cannot recognize USBaspLoader device

### ISSUE THREAD

**Issue by marklai1998** [coseyfannitutti/mysterium#5]
I'm making my own mysterium and I bought my own chip
after flashing the bootloader with usbTiny
Windows doesn't recognize the device
how can I troubleshoot it?

**Comment by coseyfannitutti** [comment]
You need to press the BOOT button on the PCB for it to be recognized when trying to flash.

If the 'make fuse' command was not run, this can also cause it to have this behavior.

If you ran both the 'make flash' and 'make fuse' commands without any errors, and it is still not working, then something on the board is not properly soldered.

If the LED is working, then you likely have shorted or cold joints on your USB data pins. Add more flux and reflow.

**Comment by marklai1998** [comment]
@coseyfannitutti Thx for the reply, I'm a newbie in electronics, thus came here for help.

What I can tell is:


1. I swapped out some parts since some are not common in my place. First one is the UMT1H4R7MDD, I swap out for a taller one, still 4.7uF 50V but its 85°C, not 105. Another one are those resistors, I cannot find 1/6w and used 1/5w instead.

2. I found the led is soldered in the opposite way, causing the light won't on, but not sure if it will cause the board not booting

3. I tried to use WinAVR at first but it won't make. After switching to another AVR toolchain, it makes, but also come with some warning, I'm not sure if the warning is critical.

make
![image](https://user-images.githubusercontent.com/18364699/81427249-1f506480-918d-11ea-8dcb-e5067da03add.png)

make flash
![image](https://user-images.githubusercontent.com/18364699/81427500-77876680-918d-11ea-99e5-60f3d29da8c9.png)

make fuse
![image](https://user-images.githubusercontent.com/18364699/81427524-7fdfa180-918d-11ea-9f1d-a02034fa35f9.png)


I'll keep investigating it, and get back to you in a few days

**Comment by marklai1998** [comment]
@coseyfannitutti  When I use WinAVR, it won't even make
wanna make sure the make file is okay
![image](https://user-images.githubusercontent.com/18364699/81444152-3ef58600-91a9-11ea-87e6-66c1bfe36019.png)

**Comment by coseyfannitutti** [comment]
You will need to [download and unzip this file](http://www.madwizard.org/download/electronics/msys-1.0-vista64.zip).
Copy msys-1.0.dll to the \utils\bin directory of your WinAVR folder

That will take care of the child died before initialization error.

**Comment by marklai1998** [comment]
![image](https://user-images.githubusercontent.com/18364699/81464615-bf41d880-91f5-11ea-8d9a-95ed014858da.png)
still no luck with the dll loaded

**Comment by coseyfannitutti** [comment]
You don't need to run the 'make' command. You only need 'make flash' and 'make fuse'.

**Comment by marklai1998** [comment]
I directly use `make flash` then `make fuse` but still no luck(using both a new chip and old chip)
I verified the soldered with a voltmeter, the USB port is working without any bridging(date + - pin are also verified to be connected)

![image](https://user-images.githubusercontent.com/18364699/81482057-e4226400-9266-11ea-832d-954e04cf7427.png)

**Comment by coseyfannitutti** [comment]
Are you certain that your crystal is 16MHz / 18pF?

Something between your USB port and your microcontroller is not right, and this appears to be a physical issue on the PCB. Without having the board physically in my hand, it will be difficult for me to troubleshoot a physical issue.

It appears that the bootloader has been flashed correctly. The bootloader works, and the PCB design works. If you had this PCB made yourself, the minimum order was likely 5. I would recommend trying to rebuild if you cannot find what is wrong on the PCB.

**Comment by marklai1998** [comment]
Yes, I'd have 5 board on my hand, I'll try to rebuild one in these few days.
Thx a lot, I'll update you after that

**Comment by marklai1998** [comment]
sorry for a long silence. I've been back and forth around those 5 board these days. 
I've been following your instruction and focus on the USB port. Greate news is that I've made 2 board working. Since 4 of my friends and I started this project. I still need to get the rest of the board working.

1 of the board act weirdly despite the USB port is soldered correctly. It starts out okay, can use for a few hours without a problem, but it stops working somehow when I reconnect the cable(and sometimes it works again by disconnecting it for a period of time then reconnect).

**Comment by Klagelied** [comment]
Hi,

I had the exact same problem with the Unknown USB Device (Device Descriptor Request Failed) Code 43. Only difference is that the problem affected my Discipline Keyboard, not my Mysterium.
Bootloader flashing and Firmware flashing worked great.

Next step was soldering the switches. After I hit the reset button, the error displayed. The board was tested before the switches were installed by me. 
I triple checked my Soldering, on the USB-C connector as well as on the other components that were directly connected to the MCU or the USB-Port.

My luck was that I got hands on a notebook that did not showed me the Unknown USB Device (Device Descriptor Request Failed) error. It seemed that some Keys were stuck in action, like they were permanently pressed - Maybe it is a security feature by Windows to disable the USB-Device with such behaviour. Resoldering the problematic switches did the trick. My Discipline now works on any Windows PC. 

Good luck on solving your issue!
