### ISSUE TITLE
Proton C support

### ISSUE THREAD

**Issue by ytkwong** [coseyfannitutti/mysterium#6]
Wondering if it was possible to directly replace the  Atmega with a proton C module?

**Comment by coseyfannitutti** [comment]
Not with the design as it is. It can be adapted to be compatible, but schematic symbol/pcb footprint of the microcontroller would need to be replaced, rows and columns reassigned, many of the resistors and the zener diodes would need to be removed, and the firmware would need to change.

It’s certainly possible and wouldn’t be too difficult of a task if you’re familiar with kicad and qmk, but it’s far from simply buying a proton c and soldering it on the board as it is.
