### ISSUE TITLE
Unable to compile on config.qmk

### ISSUE THREAD

**Issue by hugs94** [coseyfannitutti/mysterium#9]
Currently unable to compile default layout on config.qmk.

url: https://config.qmk.fm/#/coseyfannitutti/mysterium/LAYOUT_tkl_ansi

Error message:
```
error: pathspec 'lib/vusb' did not match any file(s) known to git
make: *** ine] Error 1
```

**Comment by coseyfannitutti** [comment]
This is unfortunately a QMK issue at the moment for all V-USB boards like my through hole boards, TGR Jane, or any other ATmega32A/ATmega328P based boards.

I was recently testing out some builds with yiancar for opening a third endpoint for V-USB boards to unlock the use of media keys with VIA, which were successful.

They've been working to push these changes to the main repository, and perhaps along the way some of those changes have temporarily caused a conflict. I'm sure this will be fixed soon.

For now, though, Mysterium is VIA compatible, and you can get pre-compiled firmware from caniusevia.com

For now that .hex unfortunately turns off media keys such as volume control. If you need those, shoot me a screenshot of your layout, and I can just manually create the keymap file and compile via command line with an older version of the QMK repository.

**Comment by hugs94** [comment]
I see. Okay, closing this issue as VIA should cover most use cases anyway.
